version: '3.8'

services:

  api_gateway:
    build:
      context: ./api_gateway/
      dockerfile: Dockerfile
    container_name: api_gateway
    restart: on-failure
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    depends_on:
      - tuzilastvo_service
    networks:
      - network

  tuzilastvo_service:
    image: tuzilastvo_service
    container_name: tuzilastvo_service
    build:
      context: .
      dockerfile: ./tuzilastvo_service/Dockerfile
    restart: always
    ports:
      - ${TUZILASTVO_SERVICE_PORT}:${TUZILASTVO_SERVICE_PORT}
    environment:
      TUZILASTVO_DB_HOST: ${TUZILASTVO_DB_HOST}
      TUZILASTVO_DB_PORT: ${TUZILASTVO_DB_PORT}
      TUZILASTVO_SERVICE_PORT: ${TUZILASTVO_SERVICE_PORT}
      SECRET_KEY: ${SECRET_KEY}

    depends_on:
      tuzilastvo_db:
        condition: service_started
    networks:
      - network
    volumes:
      - ./files:/usr/bin/files


  tuzilastvo_db:
    image: mongo
    container_name: tuzilastvo_db
    restart: on-failure
    networks:
      - network


networks:
  network:
    driver: bridge